ktor:
  application:
    modules:
      - app.sotchi.ApplicationKt.module
  deployment:
    port: 8080
  jwt:
    secret: "secret"
    issuer: "generated-by-sotchi-api"
    audience: "useable-by-sotchi-api-consumers"
    realm: "sotchi-api"
  database:
    url: "jdbc:h2:./dev"
    user: "root"
    password: "root"
    driver: "org.h2.Driver"

